module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
   
    fontFamily: {
      sans: ["Avenir Next Regular"],
      serif: ["Avenir Next Bold"],
    },
    fontSize: {
      tiny: "6px",
      xxxs: "10px",
      xxs: "12px",
      xs: "14px",
      sm: "16px",
      base: "18px",
      lg: "20px",
      xl: "24px",
      "2xl": "32px",
      "3xl": "36px",
      "4xl": "48px",
      "5xl": "60px",
      "6xl": "72px",
      "7xl": "5rem",
      "10xl": "10rem",
    },
    colors: {
      button: "var(--color-button-text)",
      transparent: "transparent",
      primary: {
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      secondary: {
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
      },
      accent: {
        DEFAULT: "var(--color-accent)",
        hover: "var(--color-accent-hover)",
        disabled: "var(--color-accent-disabled)",
        purple: "var(--color-purple)",
      },
      black: "#000",
      white: "#fff",
      green: "var(--color-green)",
      greenLight: "var(--color-green-light)",
      red: "var(--color-red)",
      redLight: "var(--color-red-light)",
      dark: "var(--color-dark)",
    },
    
    borderWidth: {
      DEFAULT: "1px",
      0: "0px",
      4: "4px",
      2: "2px",
    },
    extend: {
      borderRadius: {
        5: "5px",
        8: "8px",
        10: "10px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        34: "34px",
        40: "40px",
      },
      spacing: {
        300:"300px",
        400:"400px",
        500: "500px",
        600: "600px",
      },
      borderColor: {
        "color-800": "var(--color-primary-800)",
      },
      boxShadow: {
        outlineLg: "0px 4px 10px rgba(0, 0, 0, 0.1)",
        outlineMd: "4px 0px 16px #E8E8E8",
        outlineSm: "0 0 0 1pt var(--color-primary-200)",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
